### ISSUE TITLE
Include reference in docs like in backend repo

### ISSUE THREAD

**Issue by jagodek** [yaptide/for_developers#5]
Backend repo uses docs/gen_ref_pages.py to read code files and generate reference page in docs. In this repo it won't work because there is no code files. Edit script to read those files from backend repo. The possible approaches are:
 * Use git submodules
 * Use github api ot access backend repo
 * Use usual http request and scrape data ( not recommend)
Find out which approach is best and how to execute it.

**Comment by grzanka** [comment]
Another idea: in the github actions job of this (`for_developers`) repository run the `git clone` (see https://github.com/actions/checkout for details) of `yaptide\yaptide` backend repository. That will generate whats needed to have the documentation here.
